### ISSUE TITLE
File not found - Error on `v3.0.0`

### ISSUE THREAD

**Issue by GrantBirki** [cloudflare/wrangler-action#126]
# File not found

When upgrading to `v3.0.0` of this Action, I ran into the following error:

```text
Error: File not found: '/home/runner/work/_actions/cloudflare/wrangler-action/089567dec464f48755aa4c82f1e8bdcee9b07f1d/dist/index.js'
```

[failed workflow run](https://github.com/the-hideout/tarkov-dev/actions/runs/5789825425/job/15691682034#step:10:8)

I have been using this Action for a long time and just by upgrading the version to `v3.x` (no other changes) my deploy went 💥. I rolled back my changes for now to avert this error.

**Comment by AlexTMjugador** [comment]
This issue is related to https://github.com/cloudflare/wrangler-action/issues/120 and https://github.com/cloudflare/wrangler-action/issues/115. Can you check if it works well for you now? If your workflow was pinned to an earlier commit of the v3.0.0 tag, which is unlikely, you will need to update it.

**Comment by GrantBirki** [comment]
Looks to be fixed now! 🚀 

https://github.com/the-hideout/tarkov-dev/actions/runs/5800704070/job/15723348850#step:9:20

**Comment by JacobMGEvans** [comment]
Yeah I am working on automating the whole build, release, & publish process. Should prevent future issues like this, thanks for the report and follow up 😄
