### ISSUE TITLE
 You are about to publish a Workers Service that was last published via the Cloudflare Dashboard.

### ISSUE THREAD

**Issue by winstxnhdw** [cloudflare/wrangler-action#229]
I am getting the following warning.

```console
   ▲ [WARNING] You are about to publish a Workers Service that was last published via the Cloudflare Dashboard.
    Edits that have been made via the dashboard will be overridden by your local code and config.
  ? Would you like to continue?
  🤖 Using default value in non-interactive context: yes
```

It's harmless but usually if I see such a warning, I assume there's probably a way to override it, something like a `-y` flag.

**Comment by penalosa** [comment]
This warning is to flag that changes have been made to your worker manually in the dashboard since the last `wrangler deploy`. We don't have a way to suppress this warning today. Instead, we recommend using Wrangler to make changes to your Worker as a much as possible, and minimise manual changes in the dashboard (because those changes will be cleared on the next `wrangler dpeloy` and not persisted)

**Comment by winstxnhdw** [comment]
I am using `wrangler` to make the changes though.

**Comment by timoanttila** [comment]
@penalosa Is there a way to get all edits from Dashboard to local bulld before deploying the local version that overrides the Dashboard version?

**Comment by focux** [comment]
Just landed in this issue while looking for a way to pull all changes from dahboard as @timoanttila, wondering if there's a way to do it.

**Comment by timoanttila** [comment]
> wondering if there's a way to do it.

I ended up googling values for what I needed and adding them manually to the local configuration.
