### ISSUE TITLE
Support KV namespaces creating/binding

### ISSUE THREAD

**Issue by johnd0e** [cloudflare/wrangler-action#239]
I want to use some github repo as template, with [deploy button](https://developers.cloudflare.com/workers/tutorials/deploy-button/).

The problem is the original repo uses KV and has `kv_namespace` hardcoded in `wrangler.toml`.
So no surprize that `wrangler-action` fails:
- newly deployed worker has no KV namespace bound
- and it's impossible to create namespace with same id as hardcoded in `wrangler.toml`.

Possible solution:
- implement check for existence  of KV namespaces with given names
  - if not exist, then create
- correct `id` in `wrangler.toml`.

The last step looks not clean for me, perhaps better would be to refer namespaces in other ways.
E.g.:
- by value of given env var.
- or/and by their global name (like seen in web dashboard)

**Comment by carafelix** [comment]
Is there a way to not depend on wrangler.toml to bind the kv namespace?

**Comment by shakibhasan09** [comment]
Want to know too!

**Comment by jahands** [comment]
Hi!
This looks like it's an issue with workers-sdk and not wrangler-action.
While it's technically feasible to implement this within wrangler-action, it would likely be brittle and be confusing due to differing behavior from wrangler.

If this is a feature you're interested in, please create a feature request in [workers-sdk](https://github.com/cloudflare/workers-sdk/issues/new/choose)

Thanks!
