### ISSUE TITLE
Release 3.10.0 fails depending on the file system permissions

### ISSUE THREAD

**Issue by adriantrunzo** [cloudflare/wrangler-action#306]
# Description

I've started seeing the following failures with the latest release:

```
✘ [ERROR] EACCES: permission denied, mkdir '/opt/wranglerArtifacts'
```

The failures started at the same time as the 3.10.0 release. Indeed, that release references the `/opt/wranglerArtifacts` directory: https://github.com/cloudflare/wrangler-action/commit/3ec7f8943ef83351f743cfaa8763a9056ef70993#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R317.

I do not have the ability to change permissions in these runners. Setting `WRANGLER_OUTPUT_FILE_DIRECTORY` didn't have any effect.

# Expected Behavior

No failure.

# Possible Solution

- Simply ignore the new functionality if a file system error occurs
- Add a configuration option for the output directory
- Use `WRANGLER_OUTPUT_FILE_DIRECTORY`

**Comment by JadCham** [comment]
I was about to submit an issue for the exact same error. 



**Workaround**
Pin version to cloudflare/wrangler-action@v3.9.0

**What we tried**
Pinning `wranglerVersion` only to `3.78.10` in order to get around the `DEFAULT_WRANGLER_VERSION` bump but that did not work.
https://github.com/cloudflare/wrangler-action/pull/303/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L19

Which points to the issue being in the action only as @adriantrunzo mentioned https://github.com/cloudflare/wrangler-action/commit/3ec7f8943ef83351f743cfaa8763a9056ef70993#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R317

**Comment by adriantrunzo** [comment]
Thanks for sharing what you tried @JadCham. I tried with the latest version of `wrangler`, 3.12.0, in addition to an older one like you did.

I can also confirm that pinning the version to 3.9.0 is the workaround.

**Comment by kashalls** [comment]
Running into this issue with self-hosted runner's as well.

```
🚀 Running Wrangler Commands
  /home/runner/_work/_tool/node/18.20.4/x64/bin/npx wrangler pages deploy --project-name=kubernetes-schemas --branch main .
  ✘ [ERROR] EACCES: permission denied, mkdir '/opt/wranglerArtifacts'
  ```

**Comment by brianzhou13** [comment]
+1

**Comment by BRAVO68WEB** [comment]
+1

**Comment by kashalls** [comment]
Updated to v3.11.0, issue "fixed"

**Comment by BRAVO68WEB** [comment]
GG

**Comment by kashalls** [comment]
> Hello @adriantrunzo , @JadCham @kashalls . Would you be able confirm that the latest release `3.12.0` works for you?

I had a successful run on 3.12.0
